### ISSUE TITLE
Develop base schema that will apply to all yaml-based plugin interfaces

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#107]
# Requested Update

### Description
Agree upon and finalize base schema for yaml-based plugins. Schema will use OpenAPI V3 (also known as Swagger).

### Background and Motivation
Current yaml-based plugins are poorly defined and have no method for validation. We would like to build a base that will apply to all interfaces, then subschema for each individual interface.

### Alternative Solutions
- Status quo
- Fully independent schema for each type (more difficult to maintain)
  
### Checklist for Completion
* [ ] Develop a mock-up of the desired YAML
* [ ] Develop a schema that can validate the desired YAML
* [ ] Test the schema against the mock-up and ensure that the mock-up validates
* [ ] Develop YAML that will cause validation to fail to test the schema
* [ ] Maybe? Develop unit tests for the schema

**Comment by jsolbrig** [comment]
This is currently on hold. I put together the schema for this, but for the time being it is being copied from schema to schema rather than using references.

The current base schema looks like this:
```yaml
type: object
required:
  - interface
  - metadata
  - spec
properties:
  interface:
    type: string
  metadata:
    type: object
    required: [name, family, short-description, long-description]
    properties:
      name:
        type: string
      family:
        type: string
      short-description:
        type: string
      long-description:
        type: string
```
