### ISSUE TITLE
Develop schema for `boundaries` interface plugins

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#108]
# Requested Update

### Description
Agree upon and finalize a schema for `boundaries` interface plugins. This schema should include the base interface schema.

Current boundaries interface fields include:
```python
{'boundaries_dict_type',
 'coastlines_color',
 'coastlines_linewidth',
 'countries_color',
 'countries_linewidth',
 'request_coastlines',
 'request_countries',
 'request_rivers',
 'request_states',
 'rivers_color',
 'rivers_linewidth',
 'states_color',
 'states_linewidth'}
```

Proposed schema:
```yaml
$ref: base-schema  # Need to get this reference correct
spec:
  type: object
  required: [coastlines, countries, rivers, states]
  additionalParameters: false
  parameters:
    coastlines:
      type: object
      parameters:
        enabled:
          type: boolean
        color:
          type: string
          default: black
        linewidth:
          type: integer
    countries:
      type: object
      parameters:
        enabled:
          type: boolean
        color:
          type: string
        linewidth:
          type: integer
    rivers:
      type: object
      parameters:
        enabled:
          type: boolean
        color:
          type: string
        linewidth:
          type: integer
    states:
      type: object
      parameters:
        enabled:
          type: boolean
        color:
          type: string
        linewidth:
          type: integer
```

### Checklist for Completion
* [ ] Ensure that all types are correct
* [ ] Agree upon format
* [ ] Develop tests to ensure that it works correctly both for good and malformed plugins
