### ISSUE TITLE
Develop schema for `gridlines` interface plugins

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#109]
# Requested Update

### Description
Agree upon and finalize a schema for `gridlines` interface plugins. This schema should include the base interface schema.

Current gridlines interface fields include:
```python
['bottom_label',
 'grid_lat_color',
 'grid_lat_dashes',
 'grid_lat_fontsize',
 'grid_lat_linewidth',
 'grid_lat_spacing',
 'grid_lat_xoffset',
 'grid_lat_yoffset',
 'grid_lon_color',
 'grid_lon_dashes',
 'grid_lon_fontsize',
 'grid_lon_linewidth',
 'grid_lon_spacing',
 'grid_lon_xoffset',
 'grid_lon_yoffset',
 'gridlines_dict_type',
 'left_label',
 'right_label',
 'top_label']
```
Proposed schema:
```yaml
$ref: base-schema
spec:
  type: object
  additionalProperties: false
  parameters:
    labels:
      type: object
      additionalProperties: false
      parameters:
        top:
          type: boolean
          default: true
        bottom:
          type: boolean
          default: false
        left:
          type: boolean
          default: true
        right:
          type: boolean
          default: false
    latitude-lines:
      type: object
      additionalProperties: false
      parameters:
        color:
          type: string
          default: black
        dashes:
          type: array
          minItems: 2
          maxItems: 2
          items:
            type: number
          default: [4, 2]
        linewidth:
          type: integer
          default: 1
        spacing:
          type: [number, string]
          enum: [auto]
          default: auto
        fontsize:
          ???
        xoffset:
          ???
        yoffset:
          ???
    longitude-lines:
      type: object
      additionalProperties: false
      parameters:
        color:
          type: string
          default: black
        dashes:
          type: array
          minItems: 2
          maxItems: 2
          items:
            type: number
          default: [4, 2]
        linewidth:
          type: integer
          default: 1
        spacing:
          type: [number, string]
          enum: [auto]
          default: auto
        fontsize:
          ???
        xoffset:
          ???
        yoffset:
          ???
```

### Checklist for Completion
* [ ] Ensure that all types are correct
* [ ] Agree upon format
* [ ] Develop tests to ensure that it works correctly both for good and malformed plugins

**Comment by lance-wilson** [comment]
I think this should be good:
[gridline-schema.txt](https://github.com/NRLMMD-GEOIPS/geoips/files/11142996/gridline-schema.txt)

**Comment by jsolbrig** [comment]
@lance-wilson I think that, for now, we need to add `interface` and `metadata` to the top of this. I also updated the type for `linewidth` to `number` rather than `integer`. 

Can you confirm that this looks good to you? If so, once you have access to the GeoIPS workspace, can you create a branch like I showed above, then add this to `geoips/schema/gridlines.yaml`.

```yaml
type: object
required:
  - interface
  - metadata
  - spec
properties:
  interface:
    type: string
  metadata:
    type: object
    properties:
      name:
        type: string
      family:
        type: string
      short-description:
        type: string
      long-description:
        type: string
spec:
  type: object
  additionalProperties: false
  parameters:
    labels:
      type: object
      additionalProperties: false
      parameters:
        top:
          type: boolean
          default: true
        bottom:
          type: boolean
          default: false
        left:
          type: boolean
          default: true
        right:
          type: boolean
          default: false
    latitude-lines:
      type: object
      additionalProperties: false
      parameters:
        color:
          type: string
          default: black
        linestyle:
          type: array
          minItems: 2
          maxItems: 2
          items:
            type: number
          default: [4, 2]
        linewidth:
          type: number
          default: 1
        spacing:
          type: [number, string]
          enum: [auto]
          default: auto
    longitude-lines:
      type: object
      additionalProperties: false
      parameters:
        color:
          type: string
          default: black
        linestyle:
          type: array
          minItems: 2
          maxItems: 2
          items:
            type: number
          default: [4, 2]
        linewidth:
          type: number
          default: 1
        spacing:
          type: [number, string]
          enum: [auto]
          default: auto
```
