### ISSUE TITLE
Allow references between schema

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#150]
# Requested Update

### Description
Currently, the schema validator doesn't resolve references between schema. We would like to be able to have schema/base.yaml and reuse it across all of our schema. Something like:
**base.yaml**
```yaml
$id: /geoips/schema/base
type: object
required:
  - interface
  - metadata
  - spec
properties:
  interface:
    type: string
  metadata:
    type: object
    required: [name, family, short-description, long-description]
    properties:
      name:
        type: string
      family:
        type: string
      short-description:
        type: string
      long-description:
        type: string
```

**boundaries.yaml**
```yaml
$ref: /geoips/schema/base
spec:
  <boundaries spec goes here>
```

We'd also like to be able to have conditional references between `product` plugins and `product-template` plugins. Something like:
```yaml
nterface: product_inputs
metadata:
  name: ssmis
  family: standard
  short-description: "The ssmis product_inputs configuration"
  long-description:
    "The ssmis product_inputs configuration, which produces color37, 37pct, color91, 91pct, 91H, 91V, 91HW, 91H-Physical, 91H-Legacy, 
   150H, 183-1H, 183-3H, 183-7H, 190V, 19H, 19V, 37H-Legacy, 37H-Physical, 37H, and 37V products."
spec:
  products:
    - name: 150H
      variables: ["H150"]
      interp_args:
        sigmaval: 10000
      $ref: /geoips/product-templates/150H
```

where `$ref` would reference the `spec` field from this schema:
```yaml
$id: /geoips/product-templates/150H
interface: product_templates.interp-alg-cmap
metadata:
  name: 150H
  family: interp_alg_cmap
spec:
  algorithm:
    name: single_channel
    arguments:
      output_data_range: [110, 310]
      min_outbounds: crop
      max_outbounds: crop
      norm: null
      inverse: null
  mtif_type: pmw
  colormap:
    name: pmw_tb.cmap_150H
    arguments:
      data_range: [110, 310]
  interpolation:
    name: pyresample_wrappers.interp_gauss
    arguments:
      sigmaval: 10000
```
 

### Background and Motivation
*  [ OPTIONAL: Provide additional detailed information and background related to this issue ]

### Alternative Solutions
*  [ OPTIONAL: If appropriate, list alternative fixes that could be considered]
  
### Environment
*  [ IF APPROPRIATE: Corresponding repository versions ]

### Code to demonstrate issue
*  [ IF APPROPRIATE: Can include steps here to identify/demonstrate bug fix or desired feature ]

### Checklist for Completion
* [ ]
