### ISSUE TITLE
Create product_defaults schema for each interface

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#161]
# Requested Update

### Description
Each GeoIPS interface should have a `product_defaults` schema. These should be able to be referenced from more complicated schema.

#### Requirements
- Each schema must implement an `$id` field of the form `geoips/schema/plugin_templates/<family>`
- Each schema should reference `$ref: geoips/schema/base`
- Each schema must implement `spec.name`
  - `spec.name` is required
  - Schema for yaml-based interfaces should ONLY have `spec.name`
- Each schema for module-based interfaces should:
  - implement any additional fields needed
  - make use of `required` as needed
  - make use of `additionalProperties: false` or `additionalProperties: true` as needed

#### Examples

**geoips/schema/product_templates/algorithms.yaml**
```yaml
$id: geoips/schema/product_templates/algorithms
$ref: geoips/schema/base
properties:
  spec:
    type: object
    additionalProperties: false
    required:
      - name
    properties:
      name:
        type: string
      arguments:
        type: object
        additionalProperties: true
        default: {}
```

**geoips/schema/product_templates/boundaries.yaml**
```yaml
$id: geoips/schema/product_templates/boundaries
$ref: geoips/schema/base
properties:
  spec:
    type: object
    additionalProperties: false
    required:
      - name
    properties:
      name:
        type: string
```

### Checklist for Completion
Initial:
* [ ] algorithms
* [ ] colormaps
* [ ] interpolators

Future
* [ ] filename_formats
* [ ] output_formats
* [ ] readers
* [ ] title_formats
* [ ] boundaries
* [ ] gridlines
* [ ] area_def_generator
* [ ] coverage
