### ISSUE TITLE
Update ``geoips get / describe`` to add source code link for package retrieved

### ISSUE THREAD

**Issue by evrose54** [NRLMMD-GEOIPS/geoips#571]
# Requested Update

### Description
We should update the command ``geoips get package`` (later to be ``geoips describe package``) to include in its output a link to the corresponding GeoIPS Package Source Code (repo code). . For example, if we were to run ``geoips get package geoips``, we'd also include an attribute called source_code (or something similar) which would be a url to the corresponding source code for such package (in this case https://github.com/NRLMMD-GEOIPS/geoips).

### Background and Motivation
This stemmed from a conversation about #444.

**Comment by jsolbrig** [comment]
This can probably be done along with #579.

**Comment by evrose54** [comment]
This is already done actually. The name attribute name could probably be changed from ``Documentation Link`` to ``Source Code``, however the functionality is all in place.
```yaml
(geoips) (base) [evan@spring geoips]$ geoips get package geoips_clavrx

Docstring: GeoIPS CLAVR-x plugin.
Documentation Link: https://github.com/NRLMMD-GEOIPS/geoips_clavrx
GeoIPS Package: geoips_clavrx
Package Path: /local/home/evan/geoips/geoips_packages/geoips_clavrx/geoips_clavrx
Version Number: 1.12.2a0


WARNING: The GeoIPS CLI is currently under development and is subject to change.
Until this warning is removed, do not rely on the CLI to be static.
Please feel free to test the CLI and report any bugs or comments as an issue here:
https://github.com/NRLMMD-GEOIPS/geoips/issues/new/choose
```
