### ISSUE TITLE
Modify OBP workflow definition to use a list of steps, use IDs as step keys, replace `type` with `kind`, and move `kind` inside the step definition

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#937]
# Requested Update

### Description
I'd like to slightly update the`Workflow` definition. I would like to:
- Make steps a dictionary.
- Make each step's key an arbitrary identifier that can be used as an ID to reference that step from elsewhere.
- Change `type` to `kind`.
- Move `kind` inside the step definition and make it a required argument. Remove the validator that automatically sets this field.

This would look something like:

```yaml
steps:
  read_abi:
    kind: reader
    name: abi_netcdf
    arguments:
      variables: ["B01Ref", "B02Ref", "B14BT"]
  run_infrared:
    kind: algorithm
    name: single_channel
    arguments:
      variables: ["B14BT"]
      data_range: ...
```

This should also ensure that there are no duplicate IDs. Ensuring this will either require expansion of the full workflow (i.e. expansion of embedded workflows) or raising an error on the fly if a duplicate ID is encountered.

### Background and Motivation
Using the current configuration there is no good way to reference a step for the sake of overriding arguments. This will allow easily overriding steps by referencing their IDs.

### Checklist for Completion
* [ ]
