### ISSUE TITLE
Order-Based Procflow fails with `TypeError` on improperly set `arguments` field

### ISSUE THREAD

**Issue by srikanth-kumar** [NRLMMD-GEOIPS/geoips#942]
### Description

The Order-Based Procflow fails with a `TypeError` when YAML configuration includes an `arguments` key in the following scenarios: 

- The `arguments` key is present but has no value.  

``` YAML
steps:
  - reader:
      name: abi_netcdf
      arguments:   # explicitly included but left empty
```

![Image](https://github.com/user-attachments/assets/359412c3-5bff-47c2-a80e-dac4b4e84cde)

-  The `arguments` key is set to `null`

``` YAML
steps:
  - reader:
      name: abi_netcdf
      arguments: null 
```

Since null is not a mapping, Python raises the type error 

![Image](https://github.com/user-attachments/assets/22b8ca3b-5729-4c9c-bf6e-dac478616da4)

YAML -> Python -> Pydantic parsing of YAML dictionary inputs 

### Proposed Solution

*  Add a Pydantic validator on the arguments field to coerce above input cases to `{}`.   

### Code to demonstrate issue
*  [ IF APPROPRIATE: Can include steps here to identify/demonstrate bug fix or desired feature ]

### Checklist for Completion
* [x] Update / Add validator to coerce `null` input to {}
* [x] Update / Add validator to coerce empty input to {}
